In [17]:
import pandas as pd
import numpy as np

In [18]:
df = pd.read_csv("/content/mental_health_data.csv")
print(df)

                                               Indicator              Group  \
0                        Symptoms of Depressive Disorder  National Estimate
1                        Symptoms of Depressive Disorder             By Age
2                        Symptoms of Depressive Disorder             By Age
3                        Symptoms of Depressive Disorder             By Age
4                        Symptoms of Depressive Disorder             By Age
...                                                  ...                ...
16789  Symptoms of Anxiety Disorder or Depressive Dis...           By State
16790  Symptoms of Anxiety Disorder or Depressive Dis...           By State
16791  Symptoms of Anxiety Disorder or Depressive Dis...           By State
16792  Symptoms of Anxiety Disorder or Depressive Dis...           By State
16793  Symptoms of Anxiety Disorder or Depressive Dis...           By State

               State       Subgroup Phase  Time Period      Time Period Label  \
0      United States  United States     1            1   Apr 23 - May 5, 2020
1      United States  18 - 29 years     1            1   Apr 23 - May 5, 2020
2      United States  30 - 39 years     1            1   Apr 23 - May 5, 2020
3      United States  40 - 49 years     1            1   Apr 23 - May 5, 2020
4      United States  50 - 59 years     1            1   Apr 23 - May 5, 2020
...              ...            ...   ...          ...                    ...
16789       Virginia       Virginia   4.2           72  Aug 20 - Sep 16, 2024
16790     Washington     Washington   4.2           72  Aug 20 - Sep 16, 2024
16791  West Virginia  West Virginia   4.2           72  Aug 20 - Sep 16, 2024
16792      Wisconsin      Wisconsin   4.2           72  Aug 20 - Sep 16, 2024
16793        Wyoming        Wyoming   4.2           72  Aug 20 - Sep 16, 2024

      Time Period Start Date Time Period End Date  Value  Low CI  High CI  \
0                 04/23/2020           05-05-2020   23.5    22.7     24.3
1                 04/23/2020           05-05-2020   32.7    30.2     35.2
2                 04/23/2020           05-05-2020   25.7    24.1     27.3
3                 04/23/2020           05-05-2020   24.8    23.3     26.2
4                 04/23/2020           05-05-2020   23.2    21.5     25.0
...                      ...                  ...    ...     ...      ...
16789             08/20/2024           09/16/2024   20.8    17.4     24.5
16790             08/20/2024           09/16/2024   19.9    17.4     22.6
16791             08/20/2024           09/16/2024   26.3    21.5     31.4
16792             08/20/2024           09/16/2024   17.0    13.4     21.2
16793             08/20/2024           09/16/2024   25.6    19.3     32.8

      Confidence Interval Quartile Range
0             22.7 - 24.3            NaN
1             30.2 - 35.2            NaN
2             24.1 - 27.3            NaN
3             23.3 - 26.2            NaN
4             21.5 - 25.0            NaN
...                   ...            ...
16789         17.4 - 24.5      19.5-21.5
16790         17.4 - 22.6      19.5-21.5
16791         21.5 - 31.4      23.1-27.8
16792         13.4 - 21.2      16.6-19.4
16793         19.3 - 32.8      23.1-27.8

[16794 rows x 14 columns]

In [19]:
df.head()

,Indicator,Group,State,Subgroup,Phase,Time Period,Time Period Label,Time Period Start Date,Time Period End Date,Value,Low CI,High CI,Confidence Interval,Quartile Range
0,Symptoms of Depressive Disorder,National Estimate,United States,United States,1,1,"Apr 23 - May 5, 2020",04/23/2020,05-05-2020,23.5,22.7,24.3,22.7 - 24.3,NaN
1,Symptoms of Depressive Disorder,By Age,United States,18 - 29 years,1,1,"Apr 23 - May 5, 2020",04/23/2020,05-05-2020,32.7,30.2,35.2,30.2 - 35.2,NaN
2,Symptoms of Depressive Disorder,By Age,United States,30 - 39 years,1,1,"Apr 23 - May 5, 2020",04/23/2020,05-05-2020,25.7,24.1,27.3,24.1 - 27.3,NaN
3,Symptoms of Depressive Disorder,By Age,United States,40 - 49 years,1,1,"Apr 23 - May 5, 2020",04/23/2020,05-05-2020,24.8,23.3,26.2,23.3 - 26.2,NaN
4,Symptoms of Depressive Disorder,By Age,United States,50 - 59 years,1,1,"Apr 23 - May 5, 2020",04/23/2020,05-05-2020,23.2,21.5,25.0,21.5 - 25.0,NaN

In [20]:
# Shape of dataset
df.shape

(16794, 14)

In [21]:
# Checking Data Types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16794 entries, 0 to 16793
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Indicator               16794 non-null  object
 1   Group                   16794 non-null  object
 2   State                   16794 non-null  object
 3   Subgroup                16794 non-null  object
 4   Phase                   16794 non-null  object
 5   Time Period             16794 non-null  int64
 6   Time Period Label       16794 non-null  object
 7   Time Period Start Date  16794 non-null  object
 8   Time Period End Date    16794 non-null  object
 9   Value                   16087 non-null  float64
 10  Low CI                  16087 non-null  float64
 11  High CI                 16087 non-null  float64
 12  Confidence Interval     16087 non-null  object
 13  Quartile Range          11017 non-null  object
dtypes: float64(3), int64(1), object(10)
memory usage: 1.8+ MB

In [22]:
#Check Missing Values
df.isnull().sum()

Indicator                    0
Group                        0
State                        0
Subgroup                     0
Phase                        0
Time Period                  0
Time Period Label            0
Time Period Start Date       0
Time Period End Date         0
Value                      707
Low CI                     707
High CI                    707
Confidence Interval        707
Quartile Range            5777
dtype: int64

In [23]:
# Remove Unnecessary Columns
df_clean = df.drop(columns=[
"Low CI",
"High CI",
"Confidence Interval",
"Quartile Range"
])

In [24]:
# Handle Missing Values
df_clean = df_clean.dropna(subset=["Value"])

df_clean.isnull().sum()

Indicator                 0
Group                     0
State                     0
Subgroup                  0
Phase                     0
Time Period               0
Time Period Label         0
Time Period Start Date    0
Time Period End Date      0
Value                     0
dtype: int64

In [25]:
# Convert Date Columns
df_clean["Time Period Start Date"] = pd.to_datetime(df_clean["Time Period Start Date"], format='mixed')
df_clean["Time Period End Date"] = pd.to_datetime(df_clean["Time Period End Date"], format='mixed')

In [26]:
# Filter Useful Segmentation Groups
df_filtered = df_clean[
df_clean["Group"].isin([
"By Age",
"By Sex",
"By Race/Hispanic ethnicity",
"By State"
])
]

In [27]:
# Checking final dataset.
df_filtered.shape

df_filtered.head()

,Indicator,Group,State,Subgroup,Phase,Time Period,Time Period Label,Time Period Start Date,Time Period End Date,Value
1,Symptoms of Depressive Disorder,By Age,United States,18 - 29 years,1,1,"Apr 23 - May 5, 2020",2020-04-23,2020-05-05,32.7
2,Symptoms of Depressive Disorder,By Age,United States,30 - 39 years,1,1,"Apr 23 - May 5, 2020",2020-04-23,2020-05-05,25.7
3,Symptoms of Depressive Disorder,By Age,United States,40 - 49 years,1,1,"Apr 23 - May 5, 2020",2020-04-23,2020-05-05,24.8
4,Symptoms of Depressive Disorder,By Age,United States,50 - 59 years,1,1,"Apr 23 - May 5, 2020",2020-04-23,2020-05-05,23.2
5,Symptoms of Depressive Disorder,By Age,United States,60 - 69 years,1,1,"Apr 23 - May 5, 2020",2020-04-23,2020-05-05,18.4

In [28]:
#Save Clean Dataset
df_filtered.to_csv("/content/mental_health_data - Copy.csv", index=False)

print("Cleaned CSV file saved successfully ✅")

Cleaned CSV file saved successfully ✅